### PR TITLE
fix(frontend): single fetch remix feature

### LINKED ISSUE #122: Bug: Back button in PageHeader component not functioning as expected
### Description
the `Back` button or the header link  PageHeader component do not properly redirect to homepage when clicked

Image

**Note:** reproducible only webmonetization.org/tools. Also, check network for error when reproducing this

### PR DESCRIPTION
**Pull request by DarianM**
### Description

Closes #122 

When using remix's `v3_singleFetch` feature flag with webmonetization.org/tools in production, single fetch data requests are made to incorrect URLs, resulting in 404 errors.

Expected Behavior
Single fetch data requests should respect the basename configuration and request:
`https://webmonetization.org/tools/tools.data`

Requested Changes
Added manual redirect handling in Cloudflare Worker.
Disabling the feature flag is also an option

Enabled feature flag context:
https://remix.run/docs/en/main/guides/single-fetch#single-fetch

### CODE REVIEW

File: frontend/worker.ts [hunk 1]
```diff
@@ -19,6 +19,15 @@ export default {
         return Response.redirect(new URL(`${APP_BASEPATH}/`, request.url), 302)
       }
 
+      // handle single fetch data loading and streaming format requests
+      // part of v3_singleFetch feature flag
+      if (url.pathname === '/tools.data') {
```
Comment (sidvishnoi) [inline frontend/worker.ts:24]: This is the only route with such issue? Do we have an issue open in remix repo? Or maybe it was fixed in newer versions?

**Review by sidvishnoi — APPROVED** [review]
If it works, it works.

**Comment by DarianM** [comment]
> If it works, it works.

appears to be solved with ReactRouter `7.3.0`
https://github.com/remix-run/react-router/issues/12295#issuecomment-2669440359
