### PR TITLE
fix(/prob-revshare): wallet address validation

### LINKED ISSUE #188: [BUG] RevShare wallet addresses/payment pointers are not validated before generating link
### Steps to reproduce

1. Go to https://86fa4fc5-publisher-tools.webmonetization.workers.dev/tools/prob-revshare/
2. Enter an payment pointer that does not exist, but starts with $ OR https://

### Expected result

- The payment pointer should be marked as invalid and flagged accordingly

### Actual result

- The link is generated and payment pointer is considered valid

### Screenshots or videos

Image

### Additional context

_No response_

### Affected component

Revenue Share

### Device type

Desktop

### Browsers

Chrome

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by kjmitchelljr**
Resolves #188 to validate wallet addresses before generating link tag and pie chart

### CODE REVIEW

File: frontend/app/routes/prob-revshare.tsx [hunk 1]
```diff
@@ -46,24 +46,15 @@ export default function RevsharePageWrapper() {
...
-}
-
 function Revshare() {
   const navigate = useNavigate()
   const [isModalOpen, setIsModalOpen] = useState(false)
   const [importTag, setImportTag] = useState('')
   const [importError, setImportError] = useState('')
   const { shares, setShares } = useShares()
+  const [validityMap, setValidityMap] = useState<
+    Record<number, boolean | null>
```
Comment (DarianM) [inline frontend/app/routes/prob-revshare.tsx:56]: i see no benefit in using `boolean | null`, let's leave only `boolean` as type

File: frontend/app/components/redesign/hooks/useDebounceValidation.ts [hunk 2]
```diff
@@ -0,0 +1,81 @@
+import { useEffect, useState } from 'react'
+import {
+  validateAndConfirmPointer,
+  WalletAddressFormatError
+} from '@shared/utils/index'
+
+interface ValidationState {
+  isValidating: boolean
+  isValid: boolean | null
```
Comment (DarianM) [inline frontend/app/components/redesign/hooks/useDebounceValidation.ts:9]: here too, only `boolean`

File: frontend/app/components/redesign/hooks/useDebounceValidation.ts [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+        isValidating: false,
+        isValid: null,
+        error: null
+      })
+      return
+    }
+
+    setValidationState(prevState => ({
+      ...prevState,
+      isValid: null,
```
Comment (DarianM) [inline frontend/app/components/redesign/hooks/useDebounceValidation.ts:37]: then this becomes `false` instead of `null`

File: frontend/app/routes/prob-revshare.tsx [hunk 4]
```diff
@@ -133,7 +124,26 @@ function Revshare() {
...
+  )
+
+  const hasValidShares = useMemo(() => {
+    if (
+      shares.length === 0 ||
+      shares.length !== Object.keys(validityMap).length
+    ) {
+      return false
+    }
+    // Every share must have a validation result of `true`.
```
Comment (DarianM) [inline frontend/app/routes/prob-revshare.tsx:144]: remove the comment please, there are some unused imports in this file that need cleaning up too

File: frontend/app/routes/prob-revshare.tsx [hunk 5]
```diff
@@ -222,7 +233,9 @@ function Revshare() {
           </div>
         </Card>
         <div className="my-lg md:my-md">
-          <RevShareChart shares={shares} />
+          {revSharePointers && hasValidShares && (
```
Comment (DarianM) [inline frontend/app/routes/prob-revshare.tsx:236]: isn't  just `hasValidShares` enough for this check? 🤔

**Review by DarianM — CHANGES_REQUESTED** [review]
`handle remove` / onRrmove share in prob-revshare doesn't clean up the `validityMap` when a share is removed,  still contains stale validation results.
to reproduce this, have 3 valid recipients, then invalidate any one of these 3 and then delete the invalid one using the delete button.
we are left with 2 valid recipients, so the link and chart should generate

File: frontend/app/components/redesign/hooks/useDebounceValidation.ts [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+      error: null
+    }))
+
+    const validatePointer = async (pointer: string) => {
+      let finalState: Pick<ValidationState, 'isValid' | 'error'>
+
+      try {
+        await validateAndConfirmPointer(pointer)
```
[the remark this answers is not in the document]
Comment (kjmitchelljr) [reply frontend/app/components/redesign/hooks/useDebounceValidation.ts:45]: I can see that, especially since it's happening while user is typing, versus responding to a button click event. Let me play around with this idea and see what I come up with
